[project]
name = "aws-rag-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "llama-index-core>=0.14.22",
    "llama-index-embeddings-huggingface>=0.7.0",
    "llama-index-llms-google-genai>=0.9.5",
    "llama-index-storage-docstore-mongodb>=0.5.0",
    "llama-index-vector-stores-pinecone>=0.8.0",
    "pinecone>=7,<8",
    "pymongo>=4.17.0",
    "streamlit>=1.58.0",
    "torchvision>=0.27.0",
]
